"""referral/waitlist model initiation

Revision ID: 50d00d7106f2
Revises: 8f92c96d0f46
Create Date: 2026-05-21 00:28:43.954025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d00d7106f2'
down_revision: Union[str, Sequence[str], None] = '8f92c96d0f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.String(length=100), server_default='', nullable=False),
    sa.Column('x_username', sa.String(length=100), nullable=False),
    sa.Column('x_link', sa.String(length=500), server_default='', nullable=False),
    sa.Column('region', sa.String(length=30), server_default='', nullable=False),
    sa.Column('niche', sa.String(length=20), server_default='', nullable=False),
    sa.Column('other_platforms', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('referral_code', sa.String(length=16), nullable=False),
    sa.Column('referrer_id', sa.Uuid(), nullable=True),
    sa.Column('referral_code_used', sa.String(length=16), server_default='', nullable=False),
    sa.Column('total_referrals', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='submitted', nullable=False),
    sa.Column('rejection_reason', sa.Text(), server_default='', nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_user_id', sa.Uuid(), nullable=True),
    sa.Column('x_verified_previously', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("niche = '' OR niche IN ('memecoins','gamefi','trading','nfts','defi','ai_tech','daos')", name='waitlist_niche_valid'),
    sa.CheckConstraint("region = '' OR region IN ('north_america','europe','middle_east','south_asia','southeast_asia','east_asia','africa','latin_america','oceania','cis_eastern_europe')", name='waitlist_region_valid'),
    sa.CheckConstraint("status IN ('submitted', 'approved', 'rejected')", name='waitlist_status_valid'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_user_id')
    )
    op.create_index(op.f('ix_waitlist_entries_email'), 'waitlist_entries', ['email'], unique=True)
    op.create_index(op.f('ix_waitlist_entries_referral_code'), 'waitlist_entries', ['referral_code'], unique=True)
    op.create_index(op.f('ix_waitlist_entries_referral_code_used'), 'waitlist_entries', ['referral_code_used'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_status'), 'waitlist_entries', ['status'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_telegram_id'), 'waitlist_entries', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_waitlist_entries_x_username'), 'waitlist_entries', ['x_username'], unique=False)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_index(op.f('ix_waitlist_entries_x_username'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_telegram_id'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_status'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_referral_code_used'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_referral_code'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_email'), table_name='waitlist_entries')
    op.drop_table('waitlist_entries')
    # ### end Alembic commands ###
