"""create users table

Revision ID: 60597f176200
Revises:
Create Date: 2026-05-19 00:05:22.812304

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "60597f176200"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("telegram_id", sa.Integer(), nullable=True),
        sa.Column("telegram_username", sa.String(length=50), nullable=True),
        sa.Column("x_username", sa.String(length=50), nullable=True),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("credits", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column(
            "total_credits_earned", sa.Numeric(precision=12, scale=4), nullable=False
        ),
        sa.Column(
            "total_credits_spent", sa.Numeric(precision=12, scale=4), nullable=False
        ),
        sa.Column("total_engagements", sa.Integer(), nullable=False),
        sa.Column("current_streak", sa.Integer(), nullable=False),
        sa.Column("tweetscout_score", sa.Integer(), nullable=False),
        sa.Column("x_verified", sa.Boolean(), nullable=False),
        sa.Column("is_whitelisted", sa.Boolean(), nullable=False),
        sa.Column("is_banned", sa.Boolean(), nullable=False),
        sa.Column("referral_code", sa.String(length=10), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "NOT (is_whitelisted AND is_banned)", name="ban_xor_whitelist"
        ),
        sa.CheckConstraint("credits >= 0", name="credits_non_negative"),
        sa.CheckConstraint(
            "total_credits_earned >= total_credits_spent", name="earned_ge_spent"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("display_name"),
    )
    op.create_index(
        op.f("ix_users_current_streak"), "users", ["current_streak"], unique=False
    )
    op.create_index(
        op.f("ix_users_is_whitelisted"), "users", ["is_whitelisted"], unique=False
    )
    op.create_index(
        op.f("ix_users_referral_code"), "users", ["referral_code"], unique=True
    )
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    op.create_index(
        op.f("ix_users_telegram_username"), "users", ["telegram_username"], unique=False
    )
    op.create_index(op.f("ix_users_x_username"), "users", ["x_username"], unique=False)
    op.create_index(op.f("ix_users_x_verified"), "users", ["x_verified"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_x_verified"), table_name="users")
    op.drop_index(op.f("ix_users_x_username"), table_name="users")
    op.drop_index(op.f("ix_users_telegram_username"), table_name="users")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_index(op.f("ix_users_referral_code"), table_name="users")
    op.drop_index(op.f("ix_users_is_whitelisted"), table_name="users")
    op.drop_index(op.f("ix_users_current_streak"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
