"""adjusting models for credit servce

Revision ID: 8f92c96d0f46
Revises: f3d0af6f76c2
Create Date: 2026-05-20 17:07:25.327756

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8f92c96d0f46"
down_revision: Union[str, Sequence[str], None] = "f3d0af6f76c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. create the ENUM type FIRST — alter_column won't do this for us
    transaction_type_enum = sa.Enum(
        "earned",
        "spent",
        "refund",
        "admin_grant",
        "apply_penalty",
        name="transactiontype",
    )
    transaction_type_enum.create(op.get_bind(), checkfirst=True)

    # 2. then alter the column to use it
    op.alter_column(
        "transactions",
        "type",
        existing_type=sa.VARCHAR(length=20),
        type_=transaction_type_enum,
        existing_nullable=False,
        postgresql_using="type::transactiontype",
    )  # explicit cast for safety

    op.create_index(
        op.f("ix_transactions_created_at"), "transactions", ["created_at"], unique=False
    )
    op.add_column(
        "users",
        sa.Column(
            "daily_credits_earned",
            sa.Numeric(precision=12, scale=4),
            server_default="0",
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "daily_earned_reset_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "users",
        "tweetscout_score",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("users_display_name_key"), "users", type_="unique")


def downgrade() -> None:
    """Downgrade schema."""

    op.create_unique_constraint(
        op.f("users_display_name_key"),
        "users",
        ["display_name"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "users",
        "tweetscout_score",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("users", "daily_earned_reset_at")
    op.drop_column("users", "daily_credits_earned")
    op.drop_index(op.f("ix_transactions_created_at"), table_name="transactions")

    # change column back to VARCHAR
    op.alter_column(
        "transactions",
        "type",
        existing_type=sa.Enum(
            "earned",
            "spent",
            "refund",
            "admin_grant",
            "apply_penalty",
            name="transactiontype",
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )

    # then drop the ENUM type — it's no longer needed
    transaction_type_enum = sa.Enum(name="transactiontype")
    transaction_type_enum.drop(op.get_bind(), checkfirst=True)
