"""transaction table

Revision ID: f3d0af6f76c2
Revises: f8ce801fa1fc
Create Date: 2026-05-20 02:18:08.091096

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f3d0af6f76c2"
down_revision: Union[str, Sequence[str], None] = "f8ce801fa1fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("reference_id", sa.Uuid(), nullable=True),
        sa.Column("reference_type", sa.String(length=50), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "type", "idempotency_key", name="transaction_idempotency_unique"
        ),
    )
    op.create_index(
        op.f("ix_transactions_idempotency_key"),
        "transactions",
        ["idempotency_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_idempotency_key"), table_name="transactions")
    op.drop_table("transactions")
    # ### end Alembic commands ###
